openapi: 3.0.3
info:
  title: Timebank MyWork Forecast lambda functions
  description: Timebank MyWork Forecast lambda functions
  version: 1.0.0
  
security:
  - bearerAuth: []
  
paths:
  
  "/currentSprint":
    get:
      operationId: currentSprint
      summary: Get current sprint
      description: |
        Gets Forecast current sprint
      tags:
        - CurrentSprint
      responses:
        "200":
          description: Current sprint object
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CurrentSprint"
  
  "/allocations":
    get:
      operationId: listAllocations
      summary: Lists Forecast allocations
      description: |
        Lists Forecast allocations
      tags:
        - Allocations
      parameters:
        - name: personId
          required: false
          in: query
          description: Retrieve allocations for person
          schema:
            type: integer
        - name: projectId
          required: false
          in: query
          description: Retrieve allocations for project
          schema:
            type: integer
        - name: startDate
          required: true
          in: query
          description: Retrieve allocations after given date
          schema:
            type: string
            format: date
        - name: endDate
          required: true
          in: query
          description: Retrieve allocations before given date
          schema:
            type: string
            format: date
      responses:
        "200":
          description: A list of Forecast allocations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Allocations"

  "/projects":
    get:
      operationId: listProjects
      summary: Lists Forecast projects
      description: |
        Lists Forecast projects
      tags:
        - Projects
      parameters:
        - name: startDate
          required: true
          in: query
          description: Retrieve allocations after given date
          schema:
            type: string
            format: date
        - name: endDate
          required: true
          in: query
          description: Retrieve allocations before given date
          schema:
            type: string
            format: date
      responses:
        "200":
          description: A list of Forecast projects
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/Projects"
  
  "/tasks":
    get:
      operationId: listTasks
      summary: Lists Forecast tasks
      description: |
        Lists Forecast tasks
      tags:
        - Tasks
      parameters:
        - name: projectId
          required: false
          in: query
          description: Forecast project id
          schema:
            type: integer
      responses:
        "200":
          description: A list of Forecast tasks
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tasks"
  
   

components:
      
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    CurrentSprint:
      type: object
      description: Current sprint data from Forecast API
      properties:
        id:
          type: integer
        name:
          type: string
        startDate: 
          type: string
          format: date
        endDate:
          type: string
          format: date
      
    Allocations:
      type: object
      description: Allocation data from Forecast API
      properties:
        id:
          type: integer
        project:
          type: integer
        person: 
          type: integer
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        monday:
          type: integer
        tuesday:
          type: integer
        wednesday:
          type: integer
        thursday:
          type: integer
        friday:
          type: integer
        saturday:
          type: integer
        sunday:
          type: integer
        notes:
          type: string
          
    Projects:
      type: object
      description: Project data from Forecast API
      properties:
        id: 
          type: integer
        name:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
          
    Tasks:
      type: object
      description: Project task data from Forecast API
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        projectId:
          type: integer
        remaining:
          type: integer
        estimate:
          type: integer
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        assignedPersons:
          type: array
          items: 
            type: integer